# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1058, 732)
        MainWindow.setMinimumSize(QtCore.QSize(1058, 732))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setMinimumSize(QtCore.QSize(60, 20))
        self.time_label.setMaximumSize(QtCore.QSize(60, 20))
        self.time_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_label.setFont(font)
        self.time_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.gridLayout_4.addWidget(self.time_label, 0, 2, 1, 1)
        self.information_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.information_groupBox.setMinimumSize(QtCore.QSize(0, 201))
        self.information_groupBox.setMaximumSize(QtCore.QSize(16777215, 201))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.information_groupBox.setFont(font)
        self.information_groupBox.setObjectName("information_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.information_groupBox)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.to_lineEdit = QtWidgets.QLineEdit(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.to_lineEdit.setFont(font)
        self.to_lineEdit.setText("")
        self.to_lineEdit.setObjectName("to_lineEdit")
        self.gridLayout_2.addWidget(self.to_lineEdit, 3, 1, 1, 1)
        self.from_label = QtWidgets.QLabel(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.from_label.setFont(font)
        self.from_label.setObjectName("from_label")
        self.gridLayout_2.addWidget(self.from_label, 0, 0, 1, 1)
        self.sub_comboBox = QtWidgets.QComboBox(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sub_comboBox.setFont(font)
        self.sub_comboBox.setObjectName("sub_comboBox")
        self.gridLayout_2.addWidget(self.sub_comboBox, 2, 0, 1, 1)
        self.to_comboBox = QtWidgets.QComboBox(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.to_comboBox.setFont(font)
        self.to_comboBox.setObjectName("to_comboBox")
        self.to_comboBox.addItem("")
        self.to_comboBox.addItem("")
        self.to_comboBox.addItem("")
        self.to_comboBox.addItem("")
        self.to_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.to_comboBox, 1, 1, 1, 1)
        self.relation_combobox = QtWidgets.QComboBox(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.relation_combobox.setFont(font)
        self.relation_combobox.setObjectName("relation_combobox")
        self.relation_combobox.addItem("")
        self.relation_combobox.addItem("")
        self.relation_combobox.addItem("")
        self.relation_combobox.addItem("")
        self.gridLayout_2.addWidget(self.relation_combobox, 1, 2, 1, 1)
        self.relation_lineEdit = QtWidgets.QLineEdit(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.relation_lineEdit.setFont(font)
        self.relation_lineEdit.setObjectName("relation_lineEdit")
        self.gridLayout_2.addWidget(self.relation_lineEdit, 3, 2, 1, 1)
        self.from_comboBox = QtWidgets.QComboBox(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.from_comboBox.setFont(font)
        self.from_comboBox.setObjectName("from_comboBox")
        self.from_comboBox.addItem("")
        self.from_comboBox.addItem("")
        self.from_comboBox.addItem("")
        self.from_comboBox.addItem("")
        self.from_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.from_comboBox, 1, 0, 1, 1)
        self.from_lineEdit = QtWidgets.QLineEdit(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.from_lineEdit.setFont(font)
        self.from_lineEdit.setObjectName("from_lineEdit")
        self.gridLayout_2.addWidget(self.from_lineEdit, 3, 0, 1, 1)
        self.sub_relation_combobox = QtWidgets.QComboBox(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sub_relation_combobox.setFont(font)
        self.sub_relation_combobox.setObjectName("sub_relation_combobox")
        self.gridLayout_2.addWidget(self.sub_relation_combobox, 2, 2, 1, 1)
        self.to_label = QtWidgets.QLabel(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.to_label.setFont(font)
        self.to_label.setObjectName("to_label")
        self.gridLayout_2.addWidget(self.to_label, 0, 1, 1, 1)
        self.sub_to_comboBox = QtWidgets.QComboBox(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sub_to_comboBox.setFont(font)
        self.sub_to_comboBox.setObjectName("sub_to_comboBox")
        self.gridLayout_2.addWidget(self.sub_to_comboBox, 2, 1, 1, 1)
        self.relation_label = QtWidgets.QLabel(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.relation_label.setFont(font)
        self.relation_label.setObjectName("relation_label")
        self.gridLayout_2.addWidget(self.relation_label, 0, 2, 1, 1)
        self.analyze = QtWidgets.QPushButton(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.analyze.setFont(font)
        self.analyze.setObjectName("analyze")
        self.gridLayout_2.addWidget(self.analyze, 4, 0, 1, 1)
        self.show_content = QtWidgets.QPushButton(self.information_groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_content.setFont(font)
        self.show_content.setObjectName("show_content")
        self.gridLayout_2.addWidget(self.show_content, 4, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.information_groupBox, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.show_contacts = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_contacts.setFont(font)
        self.show_contacts.setObjectName("show_contacts")
        self.gridLayout.addWidget(self.show_contacts, 0, 0, 1, 1)
        self.show_relationship = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_relationship.setFont(font)
        self.show_relationship.setObjectName("show_relationship")
        self.gridLayout.addWidget(self.show_relationship, 0, 1, 1, 1)
        self.show_ownership = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_ownership.setFont(font)
        self.show_ownership.setObjectName("show_ownership")
        self.gridLayout.addWidget(self.show_ownership, 0, 2, 1, 1)
        self.show_transactios = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_transactios.setFont(font)
        self.show_transactios.setObjectName("show_transactios")
        self.gridLayout.addWidget(self.show_transactios, 0, 3, 1, 1)
        self.show_home = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_home.setFont(font)
        self.show_home.setObjectName("show_home")
        self.gridLayout.addWidget(self.show_home, 1, 0, 1, 1)
        self.show_bank_accounts = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_bank_accounts.setFont(font)
        self.show_bank_accounts.setObjectName("show_bank_accounts")
        self.gridLayout.addWidget(self.show_bank_accounts, 1, 1, 1, 1)
        self.show_cars = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_cars.setFont(font)
        self.show_cars.setObjectName("show_cars")
        self.gridLayout.addWidget(self.show_cars, 1, 2, 1, 1)
        self.show_persons = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_persons.setFont(font)
        self.show_persons.setObjectName("show_persons")
        self.gridLayout.addWidget(self.show_persons, 1, 3, 1, 1)
        self.show_phones = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_phones.setFont(font)
        self.show_phones.setObjectName("show_phones")
        self.gridLayout.addWidget(self.show_phones, 1, 4, 1, 1)
        self.show_content_table = QtWidgets.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.show_content_table.setFont(font)
        self.show_content_table.setMouseTracking(True)
        self.show_content_table.setAcceptDrops(True)
        self.show_content_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.show_content_table.setDragEnabled(False)
        self.show_content_table.setDragDropOverwriteMode(False)
        self.show_content_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.show_content_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.show_content_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.show_content_table.setObjectName("show_content_table")
        self.gridLayout.addWidget(self.show_content_table, 2, 0, 1, 5)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 0, 1, 3)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_close)
        self.menuHelp.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Big data analysis"))
        self.information_groupBox.setTitle(_translate("MainWindow", "&Information"))
        self.from_label.setText(_translate("MainWindow", "From:"))
        self.to_comboBox.setItemText(0, _translate("MainWindow", "person"))
        self.to_comboBox.setItemText(1, _translate("MainWindow", "car"))
        self.to_comboBox.setItemText(2, _translate("MainWindow", "home"))
        self.to_comboBox.setItemText(3, _translate("MainWindow", "phone"))
        self.to_comboBox.setItemText(4, _translate("MainWindow", "account"))
        self.relation_combobox.setItemText(0, _translate("MainWindow", "relationship"))
        self.relation_combobox.setItemText(1, _translate("MainWindow", "transaction"))
        self.relation_combobox.setItemText(2, _translate("MainWindow", "ownership"))
        self.relation_combobox.setItemText(3, _translate("MainWindow", "contact"))
        self.from_comboBox.setItemText(0, _translate("MainWindow", "person"))
        self.from_comboBox.setItemText(1, _translate("MainWindow", "car"))
        self.from_comboBox.setItemText(2, _translate("MainWindow", "home"))
        self.from_comboBox.setItemText(3, _translate("MainWindow", "phone"))
        self.from_comboBox.setItemText(4, _translate("MainWindow", "account"))
        self.to_label.setText(_translate("MainWindow", "To:"))
        self.relation_label.setText(_translate("MainWindow", "Relation:"))
        self.analyze.setText(_translate("MainWindow", "Analyze data"))
        self.show_content.setText(_translate("MainWindow", "Show content"))
        self.show_contacts.setText(_translate("MainWindow", "show contacts"))
        self.show_relationship.setText(_translate("MainWindow", "show relationships"))
        self.show_ownership.setText(_translate("MainWindow", "show ownership"))
        self.show_transactios.setText(_translate("MainWindow", "show transactions"))
        self.show_home.setText(_translate("MainWindow", "show home"))
        self.show_bank_accounts.setText(_translate("MainWindow", "show bank accounts"))
        self.show_cars.setText(_translate("MainWindow", "show cars"))
        self.show_persons.setText(_translate("MainWindow", "show persons"))
        self.show_phones.setText(_translate("MainWindow", "show phones"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionopen.setText(_translate("MainWindow", "&Open"))
        self.action_save.setText(_translate("MainWindow", "&Save"))
        self.action_close.setText(_translate("MainWindow", "&Close"))
        self.action_About.setText(_translate("MainWindow", "&About"))
